[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
crossterm = { workspace = true }
dirs = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
once_cell = { workspace = true }