[workspace]
resolver = "2"
members = [
    "client",
    "server"
]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
crossterm = "0.28.1"
dirs = "5.0.1"
config = "0.14.0"
serde = "1.0.210"
once_cell = "1.20.2"